package synapticloop.newznab.api.response;

/*
 * Copyright (c) 2016-2017 Synapticloop.
 * 
 * All rights reserved.
 * 
 * This code may contain contributions from other parties which, where 
 * applicable, will be listed in the default build file for the project 
 * ~and/or~ in a file named CONTRIBUTORS.txt in the root of the project.
 * 
 * This source code and any derived binaries are covered by the terms and 
 * conditions of the Licence agreement ("the Licence").  You may not use this 
 * source code or any derived binaries except in compliance with the Licence.  
 * A copy of the Licence is available in the file named LICENSE.txt shipped with 
 * this source code or binaries.
 */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fasterxml.jackson.annotation.JsonProperty;

import synapticloop.newznab.api.response.model.Register;

/**
 * The registration response encapsulates the data that is returned from the
 * registration API call. 
 */
public class RegistrationResponse extends BaseModel {
	private static final Logger LOGGER = LoggerFactory.getLogger(RegistrationResponse.class);

	@JsonProperty("register")  private Register register;

	/**
	 * Get the password generated by the indexer for this user
	 * 
	 * @return the password generated by the indexer for the user
	 */
	public String getPassword() { return this.register.getPassword(); }

	/**
	 * Get the username that was generated by the indexer for this user
	 * 
	 * @return the username that was generated by the indexer for this user
	 */
	public String getUsername() { return this.register.getUsername(); }

	/**
	 * Get the api key that was generated by the indexer for this user
	 * 
	 * @return the api key that was generated by the indexer for this user
	 */
	public String getApiKey() { return this.register.getApiKey(); }

	@Override
	public Logger getLogger() { return(LOGGER); }
}
